# This is a basic workflow to help you get started with Actions
name: Proof Reading

# pushã€ã‚‚ã—ãã¯ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆä½œæˆã§ãƒˆãƒªã‚¬ãƒ¼ã•ã‚Œã‚‹
on: [push, pull_request]

jobs:
  hello:
    # ã‚¸ãƒ§ãƒ–å
    name: Check Contents
    # ã“ã‚Œã¯ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®ã¾ã¾
    runs-on: ubuntu-latest
    steps:
      - name: hello
        uses: itoaki/study-github_actions@v1.0.0
  prComment:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment test
        uses: itoaki/action-pr_comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Nice PR!ğŸ‘
      # repoã‚’ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
#      - uses: actions/checkout@v2

      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
#      - name:  ãƒã‚§ãƒƒã‚¯prh
#        uses: itoaki/writing_tools/prh@master
